title: "My Awesome Site"
description: "A description of your site"
url: "url: "https://ingsha09.github.io/game-deals"
baseurl: "game-deals" # Remove this line if deploying to the root of a custom domain
theme: minima

markdown: kramdown
