title: Pixel Proton
     description: Games deal
     url: "https://<ingsha09>.github.io/<ingsha09>"
     baseurl: "/<your-repo>" # Remove this line if deploying to the root of a custom domain
     theme: minima

     # Build settings
     markdown: kramdown
